package com.demo.store.entity;
// Generated Feb 7, 2018 1:34:34 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CategoryXref generated by hbm2java
 */
@Entity
@Table(name = "category_xref", catalog = "store")
public class CategoryXref implements java.io.Serializable {

	private static final long serialVersionUID = -6315327377709826116L;
	private Integer id;
	private Category category;
	private Date createDate;
	private Date updateDae;

	public CategoryXref() {
	}

	public CategoryXref(Category category, Date createDate, Date updateDae) {
		this.category = category;
		this.createDate = createDate;
		this.updateDae = updateDae;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sub_category_id")
	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_dae", length = 19)
	public Date getUpdateDae() {
		return this.updateDae;
	}

	public void setUpdateDae(Date updateDae) {
		this.updateDae = updateDae;
	}

}
