package com.demo.store.entity;
// Generated Feb 7, 2018 1:34:34 PM by Hibernate Tools 5.1.0.Alpha1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Type;
import org.springframework.beans.BeanUtils;

import com.demo.store.category.CategoryRequest;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name = "category")
public class Category extends AbstractEntity implements java.io.Serializable {

	private static final long serialVersionUID = -4935596204735588189L;
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Long id;
	
	@Column(name = "name", length = 45)
	private String name;
	
	@Column(name = "url", length = 65535)
	@Type(type = "text")
	private String url;
	
	@Column(name = "external_id", length = 200)
	private String externalId;
	
	@Column(name = "description", length = 100)
	private String description;
	
	@Column(name = "long_description", length = 65535)
	@Type(type = "text")
	private String longDescription;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "active_start_date", length = 19)
	private Date activeStartDate;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "active_end_date", length = 19)
	private Date activeEndDate;

	public Category() {
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getExternalId() {
		return this.externalId;
	}

	public void setExternalId(String externalId) {
		this.externalId = externalId;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getLongDescription() {
		return this.longDescription;
	}

	public void setLongDescription(String longDescription) {
		this.longDescription = longDescription;
	}

	public Date getActiveStartDate() {
		return this.activeStartDate;
	}

	public void setActiveStartDate(Date activeStartDate) {
		this.activeStartDate = activeStartDate;
	}

	public Date getActiveEndDate() {
		return this.activeEndDate;
	}

	public void setActiveEndDate(Date activeEndDate) {
		this.activeEndDate = activeEndDate;
	}
	
	public Category (CategoryRequest categoryRequest) {
		BeanUtils.copyProperties(categoryRequest, this);
	}
}
