package com.demo.store.entity;
// Generated Feb 7, 2018 1:34:34 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Type;

/**
 * Media generated by hbm2java
 */
@Entity
@Table(name = "media", catalog = "store")
public class Media implements java.io.Serializable {

	private static final long serialVersionUID = -1966637674426679783L;
	private Integer id;
	private String title;
	private String url;
	private String tags;
	private Date createDate;
	private Date updateDate;
	private Set<ProductMediaXref> productMediaXrefs = new HashSet<ProductMediaXref>(0);
	private Set<SkuMediaXref> skuMediaXrefs = new HashSet<SkuMediaXref>(0);

	public Media() {
	}

	public Media(String title, String url, String tags, Date createDate, Date updateDate,
			Set<ProductMediaXref> productMediaXrefs, Set<SkuMediaXref> skuMediaXrefs) {
		this.title = title;
		this.url = url;
		this.tags = tags;
		this.createDate = createDate;
		this.updateDate = updateDate;
		this.productMediaXrefs = productMediaXrefs;
		this.skuMediaXrefs = skuMediaXrefs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "title", length = 200)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "url", length = 65535)
	@Type(type = "text")
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "tags", length = 45)
	public String getTags() {
		return this.tags;
	}

	public void setTags(String tags) {
		this.tags = tags;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "media")
	public Set<ProductMediaXref> getProductMediaXrefs() {
		return this.productMediaXrefs;
	}

	public void setProductMediaXrefs(Set<ProductMediaXref> productMediaXrefs) {
		this.productMediaXrefs = productMediaXrefs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "media")
	public Set<SkuMediaXref> getSkuMediaXrefs() {
		return this.skuMediaXrefs;
	}

	public void setSkuMediaXrefs(Set<SkuMediaXref> skuMediaXrefs) {
		this.skuMediaXrefs = skuMediaXrefs;
	}

}
