package com.demo.store.entity;
// Generated Feb 7, 2018 1:34:34 PM by Hibernate Tools 5.1.0.Alpha1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.springframework.beans.BeanUtils;

import com.demo.store.product.ProductResponse;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "product")
public class Product extends AbstractEntity implements java.io.Serializable {

	private static final long serialVersionUID = -2505786692891174086L;
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Long id;
	
	@Column(name = "name", length = 200)
	private String name;
	
	@Column(name = "model", length = 200)
	private String model;

	public Product() {
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getModel() {
		return this.model;
	}

	public void setModel(String model) {
		this.model = model;
	}
	
	public ProductResponse toResponse() {
		ProductResponse response = new ProductResponse();
		BeanUtils.copyProperties(this, response);
		return response;
	}
	
	public static List<ProductResponse> toLisResponse(List<Product> listProduct) {
		List<ProductResponse> responses = new ArrayList<>();
		for(Product product : listProduct) {
			ProductResponse productResponse = new ProductResponse();
			BeanUtils.copyProperties(product, productResponse);
			responses.add(productResponse);
		}
		return responses;
	}

}
