package com.demo.store.entity;
// Generated Feb 7, 2018 1:34:34 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "product", catalog = "store")
public class Product implements java.io.Serializable {

	private static final long serialVersionUID = -2505786692891174086L;
	private Integer id;
	private String name;
	private String model;
	private Date createDate;
	private Date updateDate;
	private Set<ProductAttribute> productAttributes = new HashSet<ProductAttribute>(0);
	private Set<CategoryProductXref> categoryProductXrefs = new HashSet<CategoryProductXref>(0);
	private Set<Sku> skus = new HashSet<Sku>(0);
	private Set<ProductMediaXref> productMediaXrefs = new HashSet<ProductMediaXref>(0);

	public Product() {
	}

	public Product(String name, String model, Date createDate, Date updateDate, Set<ProductAttribute> productAttributes,
			Set<CategoryProductXref> categoryProductXrefs, Set<Sku> skus, Set<ProductMediaXref> productMediaXrefs) {
		this.name = name;
		this.model = model;
		this.createDate = createDate;
		this.updateDate = updateDate;
		this.productAttributes = productAttributes;
		this.categoryProductXrefs = categoryProductXrefs;
		this.skus = skus;
		this.productMediaXrefs = productMediaXrefs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "model", length = 200)
	public String getModel() {
		return this.model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<ProductAttribute> getProductAttributes() {
		return this.productAttributes;
	}

	public void setProductAttributes(Set<ProductAttribute> productAttributes) {
		this.productAttributes = productAttributes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<CategoryProductXref> getCategoryProductXrefs() {
		return this.categoryProductXrefs;
	}

	public void setCategoryProductXrefs(Set<CategoryProductXref> categoryProductXrefs) {
		this.categoryProductXrefs = categoryProductXrefs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<Sku> getSkus() {
		return this.skus;
	}

	public void setSkus(Set<Sku> skus) {
		this.skus = skus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<ProductMediaXref> getProductMediaXrefs() {
		return this.productMediaXrefs;
	}

	public void setProductMediaXrefs(Set<ProductMediaXref> productMediaXrefs) {
		this.productMediaXrefs = productMediaXrefs;
	}

}
